spring.application.name=SOA
server.port=8081

# Configura��o do banco H2 (em mem�ria)
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=1234

# Console do H2 habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracao do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration